//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a tool.
//     Runtime Version: 1.1.4322.573
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

namespace dotNetDemo {
    using System;
    using System.Data;
    using System.Xml;
    using System.Runtime.Serialization;
    
    
    [Serializable()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Diagnostics.DebuggerStepThrough()]
    [System.ComponentModel.ToolboxItem(true)]
    public class DataSet1 : DataSet {
        
        private MsUserDataTable tableMsUser;
        
        public DataSet1() {
            this.InitClass();
            System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler = new System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
            this.Tables.CollectionChanged += schemaChangedHandler;
            this.Relations.CollectionChanged += schemaChangedHandler;
        }
        
        protected DataSet1(SerializationInfo info, StreamingContext context) {
            string strSchema = ((string)(info.GetValue("XmlSchema", typeof(string))));
            if ((strSchema != null)) {
                DataSet ds = new DataSet();
                ds.ReadXmlSchema(new XmlTextReader(new System.IO.StringReader(strSchema)));
                if ((ds.Tables["MsUser"] != null)) {
                    this.Tables.Add(new MsUserDataTable(ds.Tables["MsUser"]));
                }
                this.DataSetName = ds.DataSetName;
                this.Prefix = ds.Prefix;
                this.Namespace = ds.Namespace;
                this.Locale = ds.Locale;
                this.CaseSensitive = ds.CaseSensitive;
                this.EnforceConstraints = ds.EnforceConstraints;
                this.Merge(ds, false, System.Data.MissingSchemaAction.Add);
                this.InitVars();
            }
            else {
                this.InitClass();
            }
            this.GetSerializationData(info, context);
            System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler = new System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
            this.Tables.CollectionChanged += schemaChangedHandler;
            this.Relations.CollectionChanged += schemaChangedHandler;
        }
        
        [System.ComponentModel.Browsable(false)]
        [System.ComponentModel.DesignerSerializationVisibilityAttribute(System.ComponentModel.DesignerSerializationVisibility.Content)]
        public MsUserDataTable MsUser {
            get {
                return this.tableMsUser;
            }
        }
        
        public override DataSet Clone() {
            DataSet1 cln = ((DataSet1)(base.Clone()));
            cln.InitVars();
            return cln;
        }
        
        protected override bool ShouldSerializeTables() {
            return false;
        }
        
        protected override bool ShouldSerializeRelations() {
            return false;
        }
        
        protected override void ReadXmlSerializable(XmlReader reader) {
            this.Reset();
            DataSet ds = new DataSet();
            ds.ReadXml(reader);
            if ((ds.Tables["MsUser"] != null)) {
                this.Tables.Add(new MsUserDataTable(ds.Tables["MsUser"]));
            }
            this.DataSetName = ds.DataSetName;
            this.Prefix = ds.Prefix;
            this.Namespace = ds.Namespace;
            this.Locale = ds.Locale;
            this.CaseSensitive = ds.CaseSensitive;
            this.EnforceConstraints = ds.EnforceConstraints;
            this.Merge(ds, false, System.Data.MissingSchemaAction.Add);
            this.InitVars();
        }
        
        protected override System.Xml.Schema.XmlSchema GetSchemaSerializable() {
            System.IO.MemoryStream stream = new System.IO.MemoryStream();
            this.WriteXmlSchema(new XmlTextWriter(stream, null));
            stream.Position = 0;
            return System.Xml.Schema.XmlSchema.Read(new XmlTextReader(stream), null);
        }
        
        internal void InitVars() {
            this.tableMsUser = ((MsUserDataTable)(this.Tables["MsUser"]));
            if ((this.tableMsUser != null)) {
                this.tableMsUser.InitVars();
            }
        }
        
        private void InitClass() {
            this.DataSetName = "DataSet1";
            this.Prefix = "";
            this.Namespace = "http://www.tempuri.org/DataSet1.xsd";
            this.Locale = new System.Globalization.CultureInfo("en-US");
            this.CaseSensitive = false;
            this.EnforceConstraints = true;
            this.tableMsUser = new MsUserDataTable();
            this.Tables.Add(this.tableMsUser);
        }
        
        private bool ShouldSerializeMsUser() {
            return false;
        }
        
        private void SchemaChanged(object sender, System.ComponentModel.CollectionChangeEventArgs e) {
            if ((e.Action == System.ComponentModel.CollectionChangeAction.Remove)) {
                this.InitVars();
            }
        }
        
        public delegate void MsUserRowChangeEventHandler(object sender, MsUserRowChangeEvent e);
        
        [System.Diagnostics.DebuggerStepThrough()]
        public class MsUserDataTable : DataTable, System.Collections.IEnumerable {
            
            private DataColumn columnid;
            
            private DataColumn columnname;
            
            private DataColumn columncity;
            
            private DataColumn columncountry;
            
            internal MsUserDataTable() : 
                    base("MsUser") {
                this.InitClass();
            }
            
            internal MsUserDataTable(DataTable table) : 
                    base(table.TableName) {
                if ((table.CaseSensitive != table.DataSet.CaseSensitive)) {
                    this.CaseSensitive = table.CaseSensitive;
                }
                if ((table.Locale.ToString() != table.DataSet.Locale.ToString())) {
                    this.Locale = table.Locale;
                }
                if ((table.Namespace != table.DataSet.Namespace)) {
                    this.Namespace = table.Namespace;
                }
                this.Prefix = table.Prefix;
                this.MinimumCapacity = table.MinimumCapacity;
                this.DisplayExpression = table.DisplayExpression;
            }
            
            [System.ComponentModel.Browsable(false)]
            public int Count {
                get {
                    return this.Rows.Count;
                }
            }
            
            internal DataColumn idColumn {
                get {
                    return this.columnid;
                }
            }
            
            internal DataColumn nameColumn {
                get {
                    return this.columnname;
                }
            }
            
            internal DataColumn cityColumn {
                get {
                    return this.columncity;
                }
            }
            
            internal DataColumn countryColumn {
                get {
                    return this.columncountry;
                }
            }
            
            public MsUserRow this[int index] {
                get {
                    return ((MsUserRow)(this.Rows[index]));
                }
            }
            
            public event MsUserRowChangeEventHandler MsUserRowChanged;
            
            public event MsUserRowChangeEventHandler MsUserRowChanging;
            
            public event MsUserRowChangeEventHandler MsUserRowDeleted;
            
            public event MsUserRowChangeEventHandler MsUserRowDeleting;
            
            public void AddMsUserRow(MsUserRow row) {
                this.Rows.Add(row);
            }
            
            public MsUserRow AddMsUserRow(string id, string name, string city, string country) {
                MsUserRow rowMsUserRow = ((MsUserRow)(this.NewRow()));
                rowMsUserRow.ItemArray = new object[] {
                        id,
                        name,
                        city,
                        country};
                this.Rows.Add(rowMsUserRow);
                return rowMsUserRow;
            }
            
            public MsUserRow FindByid(string id) {
                return ((MsUserRow)(this.Rows.Find(new object[] {
                            id})));
            }
            
            public System.Collections.IEnumerator GetEnumerator() {
                return this.Rows.GetEnumerator();
            }
            
            public override DataTable Clone() {
                MsUserDataTable cln = ((MsUserDataTable)(base.Clone()));
                cln.InitVars();
                return cln;
            }
            
            protected override DataTable CreateInstance() {
                return new MsUserDataTable();
            }
            
            internal void InitVars() {
                this.columnid = this.Columns["id"];
                this.columnname = this.Columns["name"];
                this.columncity = this.Columns["city"];
                this.columncountry = this.Columns["country"];
            }
            
            private void InitClass() {
                this.columnid = new DataColumn("id", typeof(string), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnid);
                this.columnname = new DataColumn("name", typeof(string), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnname);
                this.columncity = new DataColumn("city", typeof(string), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columncity);
                this.columncountry = new DataColumn("country", typeof(string), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columncountry);
                this.Constraints.Add(new UniqueConstraint("Constraint1", new DataColumn[] {
                                this.columnid}, true));
                this.columnid.AllowDBNull = false;
                this.columnid.Unique = true;
            }
            
            public MsUserRow NewMsUserRow() {
                return ((MsUserRow)(this.NewRow()));
            }
            
            protected override DataRow NewRowFromBuilder(DataRowBuilder builder) {
                return new MsUserRow(builder);
            }
            
            protected override System.Type GetRowType() {
                return typeof(MsUserRow);
            }
            
            protected override void OnRowChanged(DataRowChangeEventArgs e) {
                base.OnRowChanged(e);
                if ((this.MsUserRowChanged != null)) {
                    this.MsUserRowChanged(this, new MsUserRowChangeEvent(((MsUserRow)(e.Row)), e.Action));
                }
            }
            
            protected override void OnRowChanging(DataRowChangeEventArgs e) {
                base.OnRowChanging(e);
                if ((this.MsUserRowChanging != null)) {
                    this.MsUserRowChanging(this, new MsUserRowChangeEvent(((MsUserRow)(e.Row)), e.Action));
                }
            }
            
            protected override void OnRowDeleted(DataRowChangeEventArgs e) {
                base.OnRowDeleted(e);
                if ((this.MsUserRowDeleted != null)) {
                    this.MsUserRowDeleted(this, new MsUserRowChangeEvent(((MsUserRow)(e.Row)), e.Action));
                }
            }
            
            protected override void OnRowDeleting(DataRowChangeEventArgs e) {
                base.OnRowDeleting(e);
                if ((this.MsUserRowDeleting != null)) {
                    this.MsUserRowDeleting(this, new MsUserRowChangeEvent(((MsUserRow)(e.Row)), e.Action));
                }
            }
            
            public void RemoveMsUserRow(MsUserRow row) {
                this.Rows.Remove(row);
            }
        }
        
        [System.Diagnostics.DebuggerStepThrough()]
        public class MsUserRow : DataRow {
            
            private MsUserDataTable tableMsUser;
            
            internal MsUserRow(DataRowBuilder rb) : 
                    base(rb) {
                this.tableMsUser = ((MsUserDataTable)(this.Table));
            }
            
            public string id {
                get {
                    return ((string)(this[this.tableMsUser.idColumn]));
                }
                set {
                    this[this.tableMsUser.idColumn] = value;
                }
            }
            
            public string name {
                get {
                    try {
                        return ((string)(this[this.tableMsUser.nameColumn]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("Cannot get value because it is DBNull.", e);
                    }
                }
                set {
                    this[this.tableMsUser.nameColumn] = value;
                }
            }
            
            public string city {
                get {
                    try {
                        return ((string)(this[this.tableMsUser.cityColumn]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("Cannot get value because it is DBNull.", e);
                    }
                }
                set {
                    this[this.tableMsUser.cityColumn] = value;
                }
            }
            
            public string country {
                get {
                    try {
                        return ((string)(this[this.tableMsUser.countryColumn]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("Cannot get value because it is DBNull.", e);
                    }
                }
                set {
                    this[this.tableMsUser.countryColumn] = value;
                }
            }
            
            public bool IsnameNull() {
                return this.IsNull(this.tableMsUser.nameColumn);
            }
            
            public void SetnameNull() {
                this[this.tableMsUser.nameColumn] = System.Convert.DBNull;
            }
            
            public bool IscityNull() {
                return this.IsNull(this.tableMsUser.cityColumn);
            }
            
            public void SetcityNull() {
                this[this.tableMsUser.cityColumn] = System.Convert.DBNull;
            }
            
            public bool IscountryNull() {
                return this.IsNull(this.tableMsUser.countryColumn);
            }
            
            public void SetcountryNull() {
                this[this.tableMsUser.countryColumn] = System.Convert.DBNull;
            }
        }
        
        [System.Diagnostics.DebuggerStepThrough()]
        public class MsUserRowChangeEvent : EventArgs {
            
            private MsUserRow eventRow;
            
            private DataRowAction eventAction;
            
            public MsUserRowChangeEvent(MsUserRow row, DataRowAction action) {
                this.eventRow = row;
                this.eventAction = action;
            }
            
            public MsUserRow Row {
                get {
                    return this.eventRow;
                }
            }
            
            public DataRowAction Action {
                get {
                    return this.eventAction;
                }
            }
        }
    }
}
